export const AWS_COGNITO_REGION =
  process.env.NEXT_PUBLIC_AWS_COGNITO_REGION || 'ap-northeast-1'

export const AWS_COGNITO_IDENTITY_POOL_ID =
  process.env.NEXT_PUBLIC_AWS_COGNITO_IDENTITY_POOL_ID || ''
export const AWS_COGNITO_USER_POOL_ID =
  process.env.NEXT_PUBLIC_AWS_COGNITO_USER_POOL_ID || ''
export const AWS_COGNITO_CLIENT_ID =
  process.env.NEXT_PUBLIC_AWS_COGNITO_CLIENT_ID || ''

export const AWS_COGNITO_ADMIN_IDENTITY_POOL_ID =
  process.env.NEXT_PUBLIC_AWS_COGNITO_ADMIN_IDENTITY_POOL_ID || ''
export const AWS_COGNITO_ADMIN_POOL_ID =
  process.env.NEXT_PUBLIC_AWS_COGNITO_ADMIN_POOL_ID || ''
export const AWS_COGNITO_ADMIN_CLIENT_ID =
  process.env.NEXT_PUBLIC_AWS_COGNITO_ADMIN_CLIENT_ID || ''

export const COGNITO_TEST_USER = {
  name: process.env.NEXT_PUBLIC_AWS_COGNITO_TEST_USER_NAME || '',
  email: process.env.NEXT_PUBLIC_AWS_COGNITO_TEST_USER_EMAIL || '',
  password: process.env.NEXT_PUBLIC_AWS_COGNITO_TEST_USER_PASSWORD || '',
}

export const AWS_COGNITO_CONFIG = {
  region: AWS_COGNITO_REGION,
  IdentityPoolId: AWS_COGNITO_IDENTITY_POOL_ID,
  UserPoolId: AWS_COGNITO_USER_POOL_ID,
  ClientId: AWS_COGNITO_CLIENT_ID,
}

export const AWS_ADMIN_COGNITO_CONFIG = {
  region: AWS_COGNITO_REGION,
  IdentityPoolId: AWS_COGNITO_ADMIN_IDENTITY_POOL_ID,
  UserPoolId: AWS_COGNITO_ADMIN_POOL_ID,
  ClientId: AWS_COGNITO_ADMIN_CLIENT_ID,
}
