import Head from 'next/head'
import styles from '@/assets/stylesheets/pages/Home.module.scss'
import { makeStyles, createStyles, Theme } from '@material-ui/core/styles'
import { Typography, Box } from '@material-ui/core'
import { useRef, useEffect } from 'react'
import { Layout } from '@/layouts'
import { headerHeight, SITE_TITLE } from '@/lib/util'
import { ProductIntroductionCardList } from '@/components/template'
import Shakehand from '@/assets/images/shakehand.svg'

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    head: {
      width: '100%',
      maxWidth: 1024,
      margin: '0 auto',
      padding: `${theme.spacing(2)}px ${theme.spacing(3)}px `,
      color: theme.palette.common.white,
    },
    fill: {
      background: theme.palette.primary.main,
    },
    flex: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: theme.spacing(3),
      flexWrap: 'wrap',
    },
    face: {
      width: theme.spacing(25),
      height: theme.spacing(25),
      overflow: 'hidden',
      borderRadius: 9999,
      border: `5px solid ${theme.palette.common.white}`,
      position: 'relative',
      dlexShrink: 0,
    },
    src: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      width: '100%',
      transform: 'translate3d(-50%, -50%, 0)',
    },
  })
)

const Home = () => {
  const classes = useStyles()
  let fillRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const resize = () => {
      const fullHeight = window.innerHeight - headerHeight
      if (!!fillRef) {
        fillRef!.current!.style.minHeight = `${fullHeight}px`
      }
    }
    resize()
  }, [])

  return (
    <Layout noShadow>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <section ref={fillRef} className={classes.fill}>
          <div className={classes.head}>
            <Box className={classes.flex}>
              <div className={classes.face}>
                <Shakehand className={classes.src} />
              </div>
              <div>
                <Typography
                  className={styles.title}
                  variant={'h1'}
                  component={'h2'}
                >
                  <a>{SITE_TITLE}とは？</a>
                </Typography>
              </div>
            </Box>
          </div>
          <div>
            <ProductIntroductionCardList />
          </div>
        </section>
        <section></section>
      </div>
    </Layout>
  )
}

export default Home
